apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: estate
  annotations:
    github.com/project-slug: AbhayPundora/estate
spec:
  type: other
  lifecycle: unknown
  owner: estateadmins
