apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: estate-team
  title: Estate Team
  description: Developers building the Full Stack Estate platform
spec:
  type: team
  profile:
    displayName: Estate Team
    email: estate-team@example.com
  children: []
  members:
    - abhay

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: abhay
  title: Abhay Pundora
spec:
  profile:
    displayName: Abhay Pundora
    email: abhay@example.com
  memberOf:
    - estate-team
